name: smartscreenhouse
services:
  db-app:
    image: postgres:17
    container_name: smartscreenhouse-db-app
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: screenhouse_app
    ports:
      - "5432:5432"
    networks:
      - smartscreenhouse-net
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
      - ./database/app/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/app/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./database/app/push_subscriptions.sql:/docker-entrypoint-initdb.d/3-push_subscriptions.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-monitoring:
    image: postgres:17
    container_name: smartscreenhouse-db-monitoring
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: screenhouse_monitoring
    ports:
      - "5433:5432"
    networks:
      - smartscreenhouse-net
    volumes:
      - postgres_monitoring_data:/var/lib/postgresql/data
      - ./database/monitoring/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/monitoring/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./database/monitoring/data:/docker-entrypoint-initdb.d/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7
    container_name: smartscreenhouse-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - smartscreenhouse-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: smartscreenhouse-mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - smartscreenhouse-net
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "127.0.0.1", "-p", "1883", "-t", "healthcheck", "-m", "ok"]
      interval: 5s
      timeout: 5s
      retries: 5


  app-service:
    build:
      context: ./services/app-service
      dockerfile: Dockerfile
    container_name: smartscreenhouse-app-service
    restart: always
    ports:
      - "8000:8000"
    networks:
      - smartscreenhouse-net
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DB_HOST=db-app
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=screenhouse_app
      - JWT_SECRET=supersecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONITORING_SERVICE_URL=http://monitoring-service:3001
      - DB_MON_HOST=db-monitoring
      - DB_MON_PORT=5433
      - DB_MON_NAME=screenhouse_monitoring
      - VAPID_PUBLIC_KEY=BNJNuE0rZ1Y11APM6NjqiA_GXXJ9kwgaorVLx5mi8iFdNWEuEUZEQ6VE4TdZAgmivXm82ZrlkjKgcMrpcryedHo
      - VAPID_PRIVATE_KEY=T1DIrC5KBvQvuFy9EVQDyiYAHr5YV6mKDBRJA6hQmpk
      - VAPID_SUBJECT=mailto:admin@screenhouse.local
    depends_on:
      db-app:
        condition: service_healthy
      db-monitoring:
        condition: service_healthy
      redis:
        condition: service_healthy

  monitoring-service:
    build:
      context: ./services/monitoring-service
      dockerfile: Dockerfile
    container_name: smartscreenhouse-monitoring-service
    restart: always
    ports:
      - "3001:3001"
    networks:
      - smartscreenhouse-net
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=db-monitoring
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=screenhouse_monitoring
      - JWT_SECRET=supersecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    depends_on:
      db-monitoring:
        condition: service_healthy
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_healthy

  fe-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartscreenhouse-fe-app
    restart: always
    ports:
      - "8080:80"
    networks:
      - smartscreenhouse-net
    depends_on:
      - app-service
      - monitoring-service

networks:
  smartscreenhouse-net:
    driver: bridge

volumes:
  postgres_app_data:
  postgres_monitoring_data:


